"""empty message

Revision ID: 692da7dffc72
Revises: 52fb161c5232
Create Date: 2021-11-21 23:12:46.845087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692da7dffc72'
down_revision = '52fb161c5232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('facebook_link', sa.Text(), nullable=True))
    op.add_column('image', sa.Column('instagram_link', sa.Text(), nullable=True))
    op.add_column('image', sa.Column('link', sa.Text(), nullable=True))
    op.alter_column('image', 'speaker',
               existing_type=sa.VARCHAR(length=163),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'speaker',
               existing_type=sa.VARCHAR(length=163),
               nullable=False)
    op.drop_column('image', 'link')
    op.drop_column('image', 'instagram_link')
    op.drop_column('image', 'facebook_link')
    # ### end Alembic commands ###
