"""empty message

Revision ID: 8f7667b35120
Revises: 3ebf4f1d3148
Create Date: 2021-11-13 13:49:35.620970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f7667b35120'
down_revision = '3ebf4f1d3148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('image')
    op.drop_table('Event')
    op.drop_table('worker')
    op.drop_table('specialization')
    op.drop_table('contact')
    op.drop_column('user', 'newsletter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('newsletter', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timeline', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('help', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.create_table('specialization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('descripition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('names', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetypes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='specialization_pkey')
    )
    op.create_table('worker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=21), autoincrement=False, nullable=False),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=21), autoincrement=False, nullable=False),
    sa.Column('instagram', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('names', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetypes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='worker_pkey')
    )
    op.create_table('Event',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Event_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('programe', sa.VARCHAR(length=4577), autoincrement=False, nullable=False),
    sa.Column('information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ends', sa.VARCHAR(length=54), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Event_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=333), autoincrement=False, nullable=False),
    sa.Column('discipline', sa.VARCHAR(length=213), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=163), autoincrement=False, nullable=False),
    sa.Column('img', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('names', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mimetypes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], name='image_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=112), autoincrement=False, nullable=True),
    sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    # ### end Alembic commands ###
